name: "🐛 Bug Report"
description: "If something isn't working as expected with Deno Deploy 🤔."
title: "[Bug]: "
labels: ["i: needs triage"]
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to file a bug report for Deno Deploy! Please fill out this form as completely as possible.

  - type: textarea
    attributes:
      label: Problem description
      description: |
        Please provide a detailed description of the issue you encountered with Deno Deploy.
      placeholder: |
        Describe the issue here.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps to reproduce
      description: |
        Provide the steps to reproduce the issue.
      placeholder: |
        1. Step 1
        2. Step 2
        3. Step 3
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: |
        Describe the expected behavior here.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Environment
      description: |
        Please provide information about your environment, such as Deno version, operating system, and any other relevant details.
      placeholder: |
        - Deno version: [e.g. v1.32.3]
        - OS: [e.g. macOS 10.15.4, Windows 10]

  - type: textarea
    attributes:
      label: Possible solution
      description: "If you have suggestions on a fix for the bug."

  - type: textarea
    attributes:
      label: Additional context
      description: "Add any other context about the problem here. Or a screenshot if applicable."

